spring:
  application:
    name: sc-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos注册地址
    gateway:
      default-filters:
        - Elapsed=true
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-resource
          uri: lb://service-resource
          order: 0
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        - id: service-consumer
          uri: lb://service-consumer
          order: 1
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
        - id: service-provider
          uri: lb://service-provider
          order: 2
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
server:
  port: 10000
logging:
  level:
    org.springframework.cloud.gateway: debug