server:
  port: 12000
  servlet:
    context-path: /uaa
spring:
  application:
    name: sc-uaa
  profiles:
    active: dev
  cloud:
    nacos:
#      config:
#        namespace: 001a11a0-a5b9-407f-8a59-68b9b1e322f8
      discovery:
        server-addr: 127.0.0.1:8848 # nacos注册地址
  main:
    allow-bean-definition-overriding: true # 可以重写bean_name
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mappings/*.xml

