spring:
  mvc:
    static-path-pattern: /** # 静态文件请求匹配方式
  resources:
    # 修改默认的静态寻址资源目录
    static-locations: classpath:/META-INF/resources/,classpath:/static/
  profiles:
    active: db,quartz
  application:
    name: service-quartz
  cloud:
    # nacos注册地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 13000

#暂设置全局日志层级为debug
logging:
  level:
    com.example: debug